services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tracking
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  service1:
    build: ./app/service_1
    ports:
      - "8005:8005"
    depends_on:
      - db

  service2:
    build: ./app/service_2
    ports:
      - "8006:8006"
    depends_on:
      - db

volumes:
  pgdata: